// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/liqi/Documents/learnCode/pomelo/node_modules/.pnpm/dumi@2.2.17_thkfpdb6upyov6moc3vdgeaiei/node_modules/dumi/theme-default/layouts/DocLayout/index.js';
